### ISSUE TITLE
runtime is not working well with the latest oasis-core

### ISSUE THREAD

**Issue by samohyes** [oasislabs/oasis-runtime#964] opened 2020-01-17 07:47 UTC
So after I build the latest oasis-core, and try to start the gateway with the command
make run-gateway
it gives me this error

`
make run-gateway
*** Starting Oasis Network Runner and Web3 gateway...
Error: unknown flag: --address
Usage:
  oasis-node debug [command]

Available Commands:
  byzantine   run some node behaviors for testing, often not honest
  storage     node storage interface utilities
  tendermint  tendermint backend utilities
  txsource    send random transactions

Flags:
  -h, --help   help for debug

Global Flags:
      --config string                       config file
      --datadir string                      data directory
      --log.file string                     log file
      --log.format [logfmt,JSON]            log format (default logfmt)
      --log.level [DEBUG,INFO,WARN,ERROR]   log level (default WARN)

Use "oasis-node debug [command] --help" for more information about a command.

unknown flag: --address
level=info module=oasis/net-runner caller=oasis.go:518 ts=2020-01-17T07:44:19.309759987Z msg="launching node" args="registry entity init --signer file --signer.dir /tmp/oasis-runtime-runner/net-runner/network/entity-1"
.buildkite/scripts/common.sh: line 12: 23078 Terminated              ${oasis_runner} --net.node.binary ${oasis_node} --net.runtime.binary ${runtime_binary} --net.runtime.loader ${runtime_loader} --net.runtime.genesis_state ${runtime_genesis} --net.keymanager.binary ${keymanager_binary} --basedir.no_temp_dir --basedir ${data_dir}
`

So I remeber everything is fine back in December. But it won't work now. This is weird.

**Comment by kostko** [comment] 2020-01-17 07:49
Seems like a duplicate of #962. The oasis-runtime has not yet been updated to use the latest oasis-core, some minor changes are needed.

**Closed by kostko** 2020-01-17 07:49 UTC
